# -*- coding: utf-8 -*-
"""meucatalagofilmes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lvzPRhucqUckn9PNBcKoHIrn0UXGjsYZ
"""

from IPython.display import display, HTML
import base64
import json

# --- [BLOCO 0: CONFIGURAÇÕES E DADOS] ---
cor_banner_inicio = "#1a1a1a"
cor_banner_fim = "#2c3e50"

filmes_storage = {
    "Criminal": {"icon": "🔪", "filmes": ["Murder on the Orient Express", "Pulp Fiction", "O agente secreto", "O Colecionador de Ossos"]},
    "Suspense": {"icon": "😰", "filmes": ["Don’t move", "Foi apenas um acidente", "O enfermeiro da noite", "Oito mulheres e um segredo"]},
    "Drama": {"icon": "🎭", "filmes": ["Nomadland", "Vidas Passadas", "O último azul", "Paradise"]},
    "+18": {"icon": "🔞", "filmes": ["A empregada", "Me chame pelo seu nome", "Sex/Life", "Azul é a cor mais quente"]},
    "Documentário": {"icon": "📽️", "filmes": ["Dear Zachary", "Planet Earth", "Alphago", "Age of Samurai"]},
    "Aventura": {"icon": "🧗", "filmes": ["Uncharted", "Fúria de titãs 1 e 2", "Predador", "Kaguya"]},
    "Guerra": {"icon": "⚔️", "filmes": ["Até o último homem", "O resgate do soldado ryan", "A Lista de Schindler", "1917"]},
    "Fantasia": {"icon": "🧙", "filmes": ["Avatar", "Frankenstein", "O troll da montanha", "A torre negra"]},
    "Ficção": {"icon": "👽", "filmes": ["Ruptura", "A grande inundação", "Spaceman", "2001: A Space Odyssey"]},
    "Romance": {"icon": "❤️", "filmes": ["Todo tempo que temos", "O prisma do amor", "Meu Eterno Talvez", "303"]},
    "Comédia Romântica": {"icon": "🥰", "filmes": ["10 Things I Hate About You", "Columbus", "Sleeping with Other People", "The big sick"]},
    "Comédia": {"icon": "😂", "filmes": ["Queime Depois de Ler", "O Dublê", "Residence", "O fantástico senhor raposo"]},
    "Animação": {"icon": "🎨", "filmes": ["Zootopia 2", "Aranhaverso 2", "Cowboy Bebop", "Sussurros do Coração"]},
    "Ação": {"icon": "💥", "filmes": ["Pecadores", "Classe dos herois fracos", "CasHero", "Máquina de guerra"]},
    "Asiático": {"icon": "🍜", "filmes": ["Alquimia das almas", "Se esse amor desaparecesse hoje", "The Handmaiden", "I Want to Eat Your Pancreas"]},
    "Terror": {"icon": "👻", "filmes": ["Donnie darko", "A hora do mal", "It a coisa", "O Iluminado"]},
    "Musical": {"icon": "🎵", "filmes": ["La la land", "Mamma Mia!", "Os Miseráveis", "O Rei do Show"]}
}
cores_lista = ["#e50914", "#ff9800", "#9c27b0", "#333333", "#009688", "#2196f3", "#795548", "#607d8b", "#4caf50", "#e91e63", "#00bcd4", "#673ab7", "#ffc107", "#3f51b5", "#8bc34a", "#f44336", "#00d2ff"]
mapeamento_cores = {cat: cores_lista[i % len(cores_lista)] for i, cat in enumerate(filmes_storage.keys())}

html_base = f'''
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <style>
        :root {{
            --bg-body: #f4f4f4; --bg-card: white; --text-main: #222;
            --banner-grad: linear-gradient(135deg, {cor_banner_inicio}, {cor_banner_fim}, #000);
        }}
        body.dark-mode {{
            --bg-body: #121212; --bg-card: #1e1e1e; --text-main: #ffffff;
        }}
        body {{ background-color: var(--bg-body); color: var(--text-main); margin: 0; padding-bottom: 150px; font-family: 'Segoe UI', sans-serif; scroll-behavior: smooth; transition: 0.3s; font-size: 1.15em; }}

        /* --- [ESTILO: BANNER] --- */
        .banner-fino {{ width: 100%; height: 200px; background: var(--banner-grad); display: flex; align-items: center; justify-content: center; color: white; position: relative; box-shadow: 0 5px 20px rgba(0,0,0,0.5); }}
        .banner-fino h1 {{ font-size: 2.8em; letter-spacing: 2px; }}

        /* --- [ESTILO: BOTOES LATERAIS FIXOS] --- */
        .btn-side {{
            position: absolute; top: 250px; padding: 20px 12px;
            border-radius: 8px; cursor: pointer; font-weight: bold; color: white; border: none;
            box-shadow: 0 4px 6px rgba(0,0,0,0.3); z-index: 100; writing-mode: vertical-rl; text-orientation: mixed; font-size: 1em;
        }}
        .btn-memo {{ left: 0; background: #ff9800; border-radius: 0 12px 12px 0; }}
        .btn-log {{ right: 0; background: #607d8b; border-radius: 12px 0 0 12px; }}

        /* --- [ESTILO: BOTAO TOPO] --- */
        .btn-topo {{ position: fixed; bottom: 40px; right: 40px; background: #2c3e50; color: white; width: 65px; height: 65px; border-radius: 50%; display: flex; align-items: center; justify-content: center; text-decoration: none; font-size: 32px; box-shadow: 0 6px 15px rgba(0,0,0,0.6); z-index: 1000; border: 3px solid #fff; transition: 0.3s; }}

        /* --- [ESTILO: PAINEL CENTRAL] --- */
        .admin-panel {{ max-width: 1200px; margin: 40px auto; background: var(--bg-card); padding: 35px; border-radius: 25px; display: flex; gap: 30px; color: var(--text-main); box-shadow: 0 15px 40px rgba(0,0,0,0.2); }}
        .admin-box {{ flex: 1; display: flex; flex-direction: column; gap: 15px; }}
        input, select, .btn-painel {{ padding: 15px; border-radius: 15px; border: 1px solid #ccc; font-weight: bold; font-family: inherit; font-size: 1em; }}

        /* Estilo para seletor desativado */
        select:disabled {{ opacity: 0.5; cursor: not-allowed; background-color: #333; }}
        body:not(.dark-mode) select:disabled {{ background-color: #eee; }}

        .btn-painel {{ cursor: pointer; border: none; color: white; transition: 0.3s; }}

        /* --- [ESTILO: CATEGORIAS E GRID] --- */
        .cat-row {{ display: flex; justify-content: center; gap: 15px; flex-wrap: wrap; margin-bottom: 20px; }}
        .cat-btn {{ padding: 12px 20px; border-radius: 10px; color: white; text-decoration: none; font-weight: bold; font-size: 0.95em; transition: 0.2s; cursor: pointer; }}

        .container {{ max-width: 1300px; margin: 0 auto; padding: 0 40px; }}
        .cat-title {{ text-align: left; margin-top: 60px; padding-bottom: 10px; font-size: 1.8em; scroll-margin: 50vh; }}

        .grid {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 25px; margin-top: 25px;
        }}
        .filme-card {{ background: var(--bg-card); padding: 20px; border-radius: 15px; display: flex; align-items: center; border-left: 8px solid; box-shadow: 0 4px 10px rgba(0,0,0,0.1); color: var(--text-main); font-size: 1.05em; }}
        .filme-card.visto {{ background: #2e7d32 !important; color: white !important; border-left-color: #1b5e20 !important; }}

        .modal {{ display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.85); z-index: 2000; }}
        .modal-content {{ background: var(--bg-card); color: var(--text-main); width: 90%; max-width: 700px; margin: 50px auto; padding: 35px; border-radius: 20px; max-height: 80vh; overflow-y: auto; }}
    </style>
</head>
<body id="topo" class="dark-mode">

    <div class="banner-fino">
        <h1>MEU CATÁLOGO DE FILMES</h1>
        <button onclick="toggleTheme()" style="position: absolute; top: 30px; left: 30px; cursor:pointer; background:rgba(255,255,255,0.1); border:2px solid #fff; color:#fff; border-radius:25px; padding:10px 20px; font-weight:bold;">🌓 MODO</button>
    </div>

    <button class="btn-side btn-memo" onclick="abrirModal('modal-memo')">MEMÓRIAS 🧡</button>
    <button class="btn-side btn-log" onclick="abrirModal('modal-log')">LOG 📋</button>

    <a href="#topo" class="btn-topo">↑</a>

    <div class="admin-panel">
        <div class="admin-box">
            <strong style="color: #4caf50;">➕ ADICIONAR</strong>
            <select id="sel-cat-add"></select>
            <input type="text" id="input-add" placeholder="Nome do filme...">
            <button class="btn-painel" onclick="adicionarFilme()" style="background:#4caf50;">SALVAR NOVO</button>
        </div>
        <div class="admin-box" style="border-left: 2px solid #555; border-right: 2px solid #555; padding: 0 25px;">
            <strong style="color: #f44336;">➖ REMOVER</strong>
            <select id="sel-cat-rem" onchange="atualizarListaRemover()"></select>
            <select id="sel-filme-rem" disabled>
                <option value="">Escolha a categoria...</option>
            </select>
            <button class="btn-painel" onclick="removerFilme()" style="background:#f44336;">DELETAR</button>
        </div>
        <div class="admin-box">
            <strong style="color: #2196f3;">🎲 SORTEAR</strong>
            <select id="sel-cat-sort"></select>
            <button class="btn-painel" onclick="sortearFilme()" style="background:#2196f3;">O QUE ASSISTIR?</button>
            <div id="res-sorteio" style="font-size:1.1em; font-weight:bold; margin-top:15px; color:#2196f3; text-align:center;"></div>
        </div>
    </div>

    <div id="menu-categorias"></div>
    <div class="container" id="conteudo-catalogo"></div>

    <div id="modal-log" class="modal" onclick="fecharModal(event, 'modal-log')">
        <div class="modal-content">
            <h2>Histórico do Sistema</h2>
            <div id="lista-logs"></div>
            <button onclick="limparStorage('meuLog')" style="margin-top:20px; width:100%; padding:15px; background:#dc3545; color:white; border:none; border-radius:12px; font-weight:bold; cursor:pointer;">LIMPAR LOGS</button>
        </div>
    </div>

    <div id="modal-memo" class="modal" onclick="fecharModal(event, 'modal-memo')">
        <div class="modal-content">
            <h2>🎬 Filmes Assistidos (Memórias)</h2>
            <div id="lista-memorias"></div>
            <button onclick="document.getElementById('modal-memo').style.display='none'" style="margin-top:20px; width:100%; padding:15px; border-radius:12px; font-weight:bold; cursor:pointer;">FECHAR</button>
        </div>
    </div>

    <script>
    const dbInicial = REPLACE_DB_INICIAL;
    const coresMapping = REPLACE_CORES;
    let db = JSON.parse(localStorage.getItem('meuDB')) || dbInicial;
    let logs = JSON.parse(localStorage.getItem('meuLog')) || [];
    let memorias = JSON.parse(localStorage.getItem('minhasMemorias')) || [];

    function registrarLog(msg) {{
        const data = new Date().toLocaleString('pt-BR');
        logs.unshift({{ data, acao: msg }});
        localStorage.setItem('meuLog', JSON.stringify(logs.slice(0, 50)));
    }}

    function registrarMemoria(nome, cat, status) {{
        const data = new Date().toLocaleString('pt-BR');
        if(status === 'visto') memorias.unshift({{ data, nome, cat }});
        else memorias = memorias.filter(m => m.nome !== nome);
        localStorage.setItem('minhasMemorias', JSON.stringify(memorias));
    }}

    function abrirModal(id) {{
        const lista = (id === 'modal-log') ? document.getElementById('lista-logs') : document.getElementById('lista-memorias');
        const dados = (id === 'modal-log') ? logs : memorias;
        lista.innerHTML = dados.map(d => `<div style="border-bottom:1px solid #555; padding:12px;"><small>${{d.data}}</small> - ${{d.acao || '<b>'+d.nome+'</b> ('+d.cat+')'}}</div>`).join('') || "Vazio";
        document.getElementById(id).style.display = 'block';
    }}
    function fecharModal(e, id) {{ if(e.target.id === id) document.getElementById(id).style.display = 'none'; }}
    function limparStorage(key) {{ if(confirm("Confirmar limpeza?")) {{ localStorage.removeItem(key); location.reload(); }} }}

    function toggleTheme() {{
        const isDark = document.body.classList.toggle('dark-mode');
        localStorage.setItem('theme', isDark ? 'dark' : 'light');
    }}

    function salvarDB() {{ localStorage.setItem('meuDB', JSON.stringify(db)); renderizarTudo(); }}

    function adicionarFilme() {{
        const cat = document.getElementById('sel-cat-add').value;
        const nome = document.getElementById('input-add').value.trim();
        if(nome && cat) {{
            db[cat].filmes.push(nome);
            registrarLog(`Adicionou: "${{nome}}" em ${{cat}}`);
            salvarDB();
            document.getElementById('input-add').value = '';
        }}
    }}

    function removerFilme() {{
        const cat = document.getElementById('sel-cat-rem').value;
        const idx = document.getElementById('sel-filme-rem').value;
        if(cat && idx !== "") {{
            const nomeFilme = db[cat].filmes[idx];
            if(confirm(`Deseja realmente remover "${{nomeFilme}}"?`)) {{
                registrarLog(`Removeu: "${{nomeFilme}}"`);
                db[cat].filmes.splice(idx, 1);
                salvarDB();
            }}
        }}
    }}

    function sortearFilme() {{
        const catSel = document.getElementById('sel-cat-sort').value;
        let pool = [];

        const filter = (c) => db[c].filmes.forEach(f => {{
            const sId = btoa(unescape(encodeURIComponent(f))).replace(/[^a-zA-Z0-9]/g, '');
            const jaVisto = localStorage.getItem('visto-' + sId);
            if(!jaVisto) pool.push({{f, c}});
        }});

        if(catSel === "TODOS") Object.keys(db).forEach(filter); else filter(catSel);

        if(pool.length > 0) {{
            const s = pool[Math.floor(Math.random()*pool.length)];
            document.getElementById('res-sorteio').innerHTML = `<strong>${{s.f}}</strong><br><small>(${{s.c}})</small>`;
            registrarLog(`Sorteou: "${{s.f}}"`);
        }} else document.getElementById('res-sorteio').innerText = "Todos vistos!";
    }}

    function marcarVisto(sId, nome, cat) {{
        const key = 'visto-' + sId;
        const status = localStorage.getItem(key) ? 'removido' : 'visto';
        if(status === 'visto') localStorage.setItem(key, 'true'); else localStorage.removeItem(key);
        registrarLog(`${{status==='visto'?'Assistiu':'Desmarcou'}}: "${{nome}}"`);
        registrarMemoria(nome, cat, status);
        renderizarTudo();
    }}

    function renderizarTudo() {{
        const menu = document.getElementById('menu-categorias');
        const conteudo = document.getElementById('conteudo-catalogo');
        const cats = Object.keys(db);

        let htmlMenu = '<div class="cat-row">';
        cats.forEach(cat => {{
            htmlMenu += `<a href="#${{cat}}" class="cat-btn" style="background:${{coresMapping[cat]}}">${{cat.toUpperCase()}}</a>`;
            if(cat === "Ficção") htmlMenu += '</div><div class="cat-row">';
        }});
        menu.innerHTML = htmlMenu + '</div>';

        conteudo.innerHTML = cats.map(cat => `
            <h3 id="${{cat}}" class="cat-title" style="color:${{coresMapping[cat]}}; border-bottom:3px solid ${{coresMapping[cat]}};">${{cat}} ${{db[cat].icon}}</h3>
            <div class="grid">
                ${{db[cat].filmes.map(f => {{
                    const sId = btoa(unescape(encodeURIComponent(f))).replace(/[^a-zA-Z0-9]/g, '');
                    const visto = localStorage.getItem('visto-'+sId) ? 'visto' : '';
                    return `<div class="filme-card ${{visto}}" style="border-left-color:${{coresMapping[cat]}}">
                        <input type="checkbox" ${{visto?'checked':''}} onchange="marcarVisto('${{sId}}','${{f}}','${{cat}}')">
                        <span style="margin-left:15px; font-weight:600;">${{f}}</span>
                    </div>`;
                }}).join('')}}
            </div>
        `).join('');

        const optGeral = cats.map(c => `<option value="${{c}}">${{c}}</option>`).join('');
        document.getElementById('sel-cat-add').innerHTML = '<option value="">Escolha...</option>' + optGeral;
        document.getElementById('sel-cat-rem').innerHTML = '<option value="">Escolha...</option>' + optGeral;
        document.getElementById('sel-cat-sort').innerHTML = '<option value="TODOS">Todas Categorias</option>' + optGeral;
    }}

    function atualizarListaRemover() {{
        const cat = document.getElementById('sel-cat-rem').value;
        const selFilme = document.getElementById('sel-filme-rem');

        if(cat) {{
            selFilme.disabled = false;
            selFilme.innerHTML = db[cat].filmes.map((f,i) => `<option value="${{i}}">${{f}}</option>`).join('');
        }} else {{
            selFilme.disabled = true;
            selFilme.innerHTML = '<option value="">Escolha a categoria...</option>';
        }}
    }}

    window.onload = () => {{ if(localStorage.getItem('theme')==='light') toggleTheme(); renderizarTudo(); }};
    </script>
</body>
</html>
'''

html_final = html_base.replace('REPLACE_DB_INICIAL', json.dumps(filmes_storage)).replace('REPLACE_CORES', json.dumps(mapeamento_cores))
with open("catalogo_filmes.html", "w", encoding="utf-8") as f: f.write(html_final)
display(HTML(f'<div style="text-align:center; padding:20px;"><a href="data:text/html;base64,{base64.b64encode(html_final.encode("utf-8")).decode("utf-8")}" target="_blank" style="background:#2c3e50; color:white; padding:15px; text-decoration:none; border-radius:8px; font-weight:bold;">LANÇAR CATÁLOGO ATUALIZADO 🚀</a></div>'))